# Generated by Django 3.2 on 2022-11-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
